# In Class Notebook, Week 05

You can click on the GitHub URL of this notebook to access the file in near-real time: https://github.com/UIUC-iSchool-DataViz/is445_oauoag_spring2023/blob/master/week05/inClass_week05.ipynb 

Or you can copy-paste into the nbviewer interface for a plain-text rendering:

https://kokes.github.io/nbviewer.js/viewer.html

In [1]:
import numpy as np
import ipywidgets 
import bqplot

In [5]:
# 1. Data
x = np.arange(100) # integers 0-99
y = np.random.random(100) # random numbers centered around 0.5

In [7]:
# 2. Scales
bqplot.LinearScale?

In [8]:
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

In [9]:
# 3. Marks
bqplot.Lines?

In [10]:
line = bqplot.Lines(x=x, y=y,
                   scales={'x':x_sc, 'y':y_sc})

In [12]:
# 4. Interactivity -- not yet!

In [16]:
bqplot.Axis?

In [17]:
# 5. Axes (don't forget these like I did!)
ax_x = bqplot.Axis(scale=x_sc, label='X Value')
ax_y = bqplot.Axis(scale=y_sc, label='Y Value', orientation='vertical')

In [13]:
bqplot.Figure?

In [18]:
fig = bqplot.Figure(marks=[line], axes = [ax_x, ax_y])
fig

Figure(axes=[Axis(label='X Value', scale=LinearScale(), side='bottom'), Axis(label='Y Value', orientation='ver…

In [19]:
bqplot.interacts?

In [20]:
bqplot.interacts.PanZoom?

In [21]:
pz = bqplot.interacts.PanZoom(scales={'x':[x_sc], 'y':[y_sc]})

In [22]:
fig = bqplot.Figure(marks=[line], axes=[ax_x, ax_y], interaction=pz)
fig

Figure(axes=[Axis(label='X Value', scale=LinearScale(), side='bottom'), Axis(label='Y Value', orientation='ver…

In [23]:
# random scatter plot

# 1. Data
x = np.random.random(100)
y = np.random.random(100)

In [26]:
# 2. scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# 3. axis!
x_ax = bqplot.Axis(scale = x_sc, label='X')
y_ax = bqplot.Axis(scale= y_sc, label='Y', orientation='vertical')

In [27]:
bqplot.Scatter?

In [28]:
# 4. mark = scatter
scatters = bqplot.Scatter(x=x, y=y,
                         scales = {'x':x_sc, 'y':y_sc})

In [29]:
bqplot.interacts.FastIntervalSelector?

In [30]:
# 5. interactions
selector = bqplot.interacts.FastIntervalSelector(scale=x_sc, marks=[scatters])

In [31]:
fig = bqplot.Figure(marks=[scatters], axes=[x_ax,y_ax], interaction=selector)
fig

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

In [33]:
selector.selected

array([0.04430574, 0.52745323])

In [34]:
scatters.selected_style = {'fill':'red', 'stroke':'yellow'}

## Higher dimensions -- 2D data!

In [35]:
# 1. data
data = np.random.random((10,10))

In [37]:
data.shape

(10, 10)

In [38]:
bqplot.GridHeatMap?

In [41]:
bqplot.ColorScale?

In [44]:
# 2. scales
col_sc = bqplot.ColorScale(scheme='Reds') # <3
# x/y

# 3. axis

# 4. Mark - heatmap
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# 5. interactions

fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.57196…

In [45]:
# 2. scales
col_sc = bqplot.ColorScale(scheme='Reds') # <3
# x/y

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical',
                         side='right')

# 4. Mark - heatmap
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# 5. interactions

fig = bqplot.Figure(marks=[heat_map], axes=[col_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right')], fig_margin={'t…

In [46]:
# 2. scales
col_sc = bqplot.ColorScale(scheme='Reds') # <3
x_sc = bqplot.OrdinalScale() # ordered bins
y_sc = bqplot.OrdinalScale()

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark - heatmap
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# 5. interactions

fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

In [48]:
# 2. scales
col_sc = bqplot.ColorScale(scheme='Reds') # <3
x_sc = bqplot.OrdinalScale() # ordered bins
y_sc = bqplot.OrdinalScale()

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark - heatmap
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc,
                                                 'row':y_sc,
                                                 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'blue'})

# 5. interactions

fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

In [49]:
heat_map.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'anchor_style',
 'apply_clip',
 'color',
 'column',
 'column_align',
 'display_format',
 'display_legend',
 'enable_hover',
 'font_style',
 'interactions',
 'labels',
 'null_color',
 'opacity',
 'preserve_domain',
 'row',
 'row_align',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [52]:
heat_map.selected

array([[1, 9]])

In [53]:
def on_selected(change):
    print(change)

In [54]:
# 2. scales
col_sc = bqplot.ColorScale(scheme='Reds') # <3
x_sc = bqplot.OrdinalScale() # ordered bins
y_sc = bqplot.OrdinalScale()

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark - heatmap
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc,
                                                 'row':y_sc,
                                                 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'blue'})

# 5. interactions
heat_map.observe(on_selected,'selected')

fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

{'name': 'selected', 'old': None, 'new': array([[0, 0]]), 'owner': GridHeatMap(color=array([[0.57196378, 0.57311676, 0.00149513, 0.86523861, 0.90569127,
        0.61564876, 0.98602322, 0.6210563 , 0.38605484, 0.53999976],
       [0.65609949, 0.71866496, 0.69498689, 0.03453116, 0.66345344,
        0.31527374, 0.34837166, 0.38694171, 0.20862062, 0.1700008 ],
       [0.69187381, 0.71106791, 0.27198929, 0.78230318, 0.32447487,
        0.75507887, 0.07122043, 0.10769643, 0.99347394, 0.46063031],
       [0.36568771, 0.39118138, 0.16432005, 0.58701207, 0.29333222,
        0.18759281, 0.39123524, 0.79576756, 0.67125323, 0.62060612],
       [0.8402376 , 0.28653118, 0.30236414, 0.58837018, 0.117496  ,
        0.35637885, 0.81188951, 0.88446284, 0.34081735, 0.94033622],
       [0.65726774, 0.69238217, 0.50013654, 0.03158525, 0.59343462,
        0.69570894, 0.34021872, 0.28246946, 0.01279622, 0.05190139],
       [0.0412112 , 0.89718053, 0.07367713, 0.94208456, 0.3339338 ,
        0.98729352, 0.032

In [55]:
def on_selected(change):
    print(change['owner'].selected)
    
# 2. scales
col_sc = bqplot.ColorScale(scheme='Reds') # <3
x_sc = bqplot.OrdinalScale() # ordered bins
y_sc = bqplot.OrdinalScale()

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark - heatmap
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc,
                                                 'row':y_sc,
                                                 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'blue'})

# 5. interactions
heat_map.observe(on_selected,'selected')

fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

[[0 0]]
[[1 1]]
[[2 1]]
[[1 2]]
[[3 3]]
[[2 3]]
[[1 3]]
[[1 4]
 [1 3]]
[[2 3]
 [1 3]]
[[2 4]
 [1 3]
 [1 4]
 [2 3]]
[[4 4]
 [1 3]
 [1 4]
 [2 3]
 [2 4]
 [3 3]
 [3 4]
 [4 3]]


In [57]:
def on_selected(change):
    if len(change['owner'].selected) == 1: # only selections of 1 tile
        print(change['owner'].selected[0])
    
# 2. scales
col_sc = bqplot.ColorScale(scheme='Reds') # <3
x_sc = bqplot.OrdinalScale() # ordered bins
y_sc = bqplot.OrdinalScale()

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark - heatmap
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc,
                                                 'row':y_sc,
                                                 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'blue'})

# 5. interactions
heat_map.observe(on_selected,'selected')

fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

[1 0]
[3 0]
[1 1]
[4 4]
[5 3]


In [58]:
heat_map.selected[0]

array([5, 3])

In [59]:
i,j = heat_map.selected[0]
data[i,j]

0.03158525366078735

In [60]:
selectedLabel = ipywidgets.Label()

In [61]:
selectedLabel

Label(value='')

In [62]:
def on_selected(change):
    if len(change['owner'].selected) == 1: # only selections of 1 tile
        #print(change['owner'].selected[0])
        i,j = change['owner'].selected[0]
        v = data[i,j]
        selectedLabel.value = 'Data Value = ' + str(v)
    
# 2. scales
col_sc = bqplot.ColorScale(scheme='Reds') # <3
x_sc = bqplot.OrdinalScale() # ordered bins
y_sc = bqplot.OrdinalScale()

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark - heatmap
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc,
                                                 'row':y_sc,
                                                 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'blue'})

# 5. interactions
heat_map.observe(on_selected,'selected')

fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

In [63]:
selectedLabel = ipywidgets.Label() # label

def on_selected(change):
    if len(change['owner'].selected) == 1: # only selections of 1 tile
        #print(change['owner'].selected[0])
        i,j = change['owner'].selected[0]
        v = data[i,j]
        selectedLabel.value = 'Data Value = ' + str(v) # change label value
    
# 2. scales
col_sc = bqplot.ColorScale(scheme='Reds') # <3
x_sc = bqplot.OrdinalScale() # ordered bins
y_sc = bqplot.OrdinalScale()

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark - heatmap
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc,
                                                 'row':y_sc,
                                                 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'blue'})

# 5. interactions
heat_map.observe(on_selected,'selected')

fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
#fig
dashboard = ipywidgets.VBox([selectedLabel,fig])
dashboard

## Into the 3rd dimension!

In [68]:
# 1. data
data3d = np.random.random((10,10,20))

In [69]:
data3d.shape

(10, 10, 20)

In [70]:
i,j = 0,0
data3d[i,j,:]

array([0.6885316 , 0.29836129, 0.11798487, 0.82373328, 0.7365532 ,
       0.1237338 , 0.02601242, 0.36682633, 0.32193008, 0.44251162,
       0.22068222, 0.47956926, 0.08773204, 0.31041898, 0.05131996,
       0.43448892, 0.40361746, 0.04211452, 0.14480681, 0.06275652])

In [76]:
np.sum(data3d, axis=2)

array([[ 6.18368518,  9.61338104, 10.96690046, 11.53144997,  8.86398436,
         9.3396218 ,  9.23157282,  9.31153257, 10.30459442, 10.40190903],
       [11.0421513 , 11.88451716,  8.18577977, 11.07033597, 10.03656393,
        10.33800599,  9.06644963, 10.06403757,  8.7981288 ,  9.51526208],
       [11.7626133 ,  9.52007353, 10.49883354, 10.68879533, 11.29026501,
         9.79126904, 11.34712628,  8.13349732, 10.11241946,  9.92373768],
       [12.04458982,  9.68327946,  6.49678405, 10.15762551, 10.70059888,
        12.14989429, 11.13793749,  7.55834813,  8.78951559, 10.15550841],
       [10.22082772,  7.8715692 , 10.16792694,  9.65525759, 10.01844099,
         9.90680124, 10.8264033 ,  8.05584431, 10.18831859, 10.12035508],
       [ 9.93376153, 10.41065755,  9.20752656, 10.39347499, 10.09992112,
         8.09112852, 10.2030846 ,  6.60555658,  9.44120928, 11.83074363],
       [ 7.79884596,  7.89520842, 11.30705573, 10.80846017,  7.95269458,
        11.44081613, 10.84706646, 10.16173884

In [78]:
selectedLabel = ipywidgets.Label() # label

def on_selected(change):
    if len(change['owner'].selected) == 1: # only selections of 1 tile
        #print(change['owner'].selected[0])
        i,j = change['owner'].selected[0]
        v = np.sum(data3d[i,j,:])
        selectedLabel.value = 'Summed Data Value = ' + str(v) # change label value
    
# 2. scales
col_sc = bqplot.ColorScale(scheme='Reds') # <3
x_sc = bqplot.OrdinalScale() # ordered bins
y_sc = bqplot.OrdinalScale()

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark - heatmap
heat_map = bqplot.GridHeatMap(color=np.sum(data3d,axis=2), scales={'color':col_sc,
                                                 'row':y_sc,
                                                 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'blue'})

# 5. interactions
heat_map.observe(on_selected,'selected')

fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
#fig
dashboard = ipywidgets.VBox([selectedLabel,fig])
dashboard

In [85]:
# 1. data - fake selection
i,j = 0,0
data3d[i,j,:]

array([0.6885316 , 0.29836129, 0.11798487, 0.82373328, 0.7365532 ,
       0.1237338 , 0.02601242, 0.36682633, 0.32193008, 0.44251162,
       0.22068222, 0.47956926, 0.08773204, 0.31041898, 0.05131996,
       0.43448892, 0.40361746, 0.04211452, 0.14480681, 0.06275652])

In [86]:
# 2. scales
x_sch = bqplot.LinearScale()
y_sch = bqplot.LinearScale()

# 3. axis
x_axh = bqplot.Axis(scale=x_sch, label='Value of 3rd axis')
y_axh = bqplot.Axis(scale=y_sch, orientation='vertical', label='Frequency')

In [87]:
bqplot.Hist?

In [88]:
# 4. Marks
hist = bqplot.Hist(sample=data[i,j,:], normalized=False, # counts instead of density
                  scales={'sample':x_sch, 'count':y_sch}, bins=5)

In [89]:
# 5. no interactivity here

In [90]:
figh = bqplot.Figure(marks=[hist], axes=[x_axh, y_axh])
figh

Figure(axes=[Axis(label='Value of 3rd axis', scale=LinearScale(), side='bottom'), Axis(label='Frequency', orie…

In [91]:
hist.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'apply_clip',
 'bins',
 'colors',
 'count',
 'display_legend',
 'enable_hover',
 'interactions',
 'labels',
 'midpoints',
 'normalized',
 'opacities',
 'preserve_domain',
 'sample',
 'scales',
 'scales_metadata',
 'selected',
 'selected_style',
 'stroke',
 'tooltip',
 'tooltip_location',
 'tooltip_style',
 'unselected_style',
 'visible']

In [92]:
hist.sample

array([0.10905674, 0.15914006, 0.02626777, 0.76554427, 0.65574016,
       0.38765294, 0.98033814, 0.18625341, 0.60211685, 0.72884796,
       0.63671672, 0.58536022, 0.01077411, 0.92605352, 0.79941792,
       0.46424111, 0.48309859, 0.85050127, 0.83177782, 0.8223663 ])

In [ ]:
selectedLabel = ipywidgets.Label() # label

def on_selected(change):
    if len(change['owner'].selected) == 1: # only selections of 1 tile
        i,j = change['owner'].selected[0] # grabbing the indicies of the heat map
        # updating the value of the widget
        v = np.sum(data3d[i,j,:])
        selectedLabel.value = 'Summed Data Value = ' + str(v) # change label value
    
# 2. scales
col_sc = bqplot.ColorScale(scheme='Reds') # <3
x_sc = bqplot.OrdinalScale() # ordered bins
y_sc = bqplot.OrdinalScale()

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc)
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical')

# 4. Mark - heatmap
heat_map = bqplot.GridHeatMap(color=np.sum(data3d,axis=2), scales={'color':col_sc,
                                                 'row':y_sc,
                                                 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'blue'})

# 5. interactions
heat_map.observe(on_selected,'selected')

fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
#fig
dashboard = ipywidgets.VBox([selectedLabel,fig])
dashboard